const mongoose=require("mongoose")
const loanSchema=new mongoose.Schema({
    loannumber:{
        type:Number,
        required:true
    },
    loancreatedAt:{
        type:Date,
        required:true,
        default:Date.now
    },
    customer_id:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:'customerModel'
    },
    lineman_id:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:'lineManNamemodel'
    },
    weekno:{
        type:Number,
        required:false
    },
    bookno:{
        type:Number,
        required:false
    },
    lineno:{
        type:Number,
        required:true
    },
    document:{
        type:String,
        required:false
    },
    cheque:{
        type:String,
        required:false
    },
    weekcount:{
        type:Number,
        required:true
    },
    startdate:{
        type:Date,
        required:true
    },
    givendate:{
        type:Date,
        required:true
    },
    duedate:{
        type:Date,
        required:true
    },
    finisheddate:{
        type:Date,
        required:true
    },
    givenamount:{
        type:Number,
        required:true
    },
    documentamount:{
        type:Number,
        required:true
    },
    interestamount:{
        type:Number,
        required:true
    },
    totalamount:{
        type:Number,
        required:true
    },
    dueamount:{
        type:Number,
        required:true
    },
     paidamount:{
        type:Number,
        required:true
     }   
})
module.exports=mongoose.model("LoanTable",loanSchema)